### ISSUE TITLE
All images are converted to gray scale

### ISSUE THREAD

**Issue by MBSM110** [ZhouKai90/face-detection-ssd-caffe#1]
cf_ssd_detector.cpp - line 118 - preprocess function
if (img.channels() == 3 || img.channels() == 1) should be replaced by if (img.channels() == 3 && numChannles_ == 1)

**Comment by ZhouKai90** [comment]
I used 3 channels RGB images for training.  Didn't convert all images to gray. So "if (img.channels() == 3 || img.channels() == 1) "should be replaced by "if (img.channels() == 3 && numChannles_ == 1)". It's a BUG. thanks
